<?php

declare(strict_types=1);

namespace App\Support;

final class ServiceTypeCatalog
{
    /**
     * @return array<int, array{name: string, category: string, description: string, requires_admin_assignment?: bool, default_brief_template?: string}>
     */
    public static function items(): array
    {
        return [
            ['name' => 'Website Development', 'category' => 'Software Engineering', 'description' => 'Business websites, corporate websites, portfolio websites, landing pages, and custom web builds.', 'default_brief_template' => 'Describe the type of website you need, the pages or sections you expect, and the outcome you want for the business or project.'],
            ['name' => 'Web Application Development', 'category' => 'Custom Software Development', 'description' => 'Interactive web applications, internal portals, dashboards, and business workflow systems built for browser-based use.'],
            ['name' => 'Website Design', 'category' => 'Website Design', 'description' => 'Website interface design, layout design, landing page design, and conversion-focused page planning.'],
            ['name' => 'Website Redesign', 'category' => 'Website Design', 'description' => 'Refresh an existing website with improved structure, look, messaging, and usability.'],
            ['name' => 'Website Maintenance', 'category' => 'Website Maintenance', 'description' => 'Routine updates, fixes, content changes, performance care, and ongoing website support.'],
            ['name' => 'E-Commerce Development', 'category' => 'E-Commerce Development', 'description' => 'Online stores, product catalogs, checkout flows, payment integration, and order management.'],
            ['name' => 'WordPress Development', 'category' => 'WordPress Development', 'description' => 'WordPress websites, theme customization, plugin setup, and content-managed web builds.'],
            ['name' => 'Frontend Development', 'category' => 'Frontend Development', 'description' => 'User-facing web interfaces using modern frontend technologies and clean responsive layouts.'],
            ['name' => 'Backend Development', 'category' => 'Backend Development', 'description' => 'Server-side logic, APIs, data flow, integrations, and business rules implementation.'],
            ['name' => 'Full Stack Development', 'category' => 'Full Stack Development', 'description' => 'End-to-end product development across frontend, backend, integrations, and deployment.'],
            ['name' => 'Custom Software Development', 'category' => 'Custom Software Development', 'description' => 'Tailored systems and software products built around a specific workflow or business need.'],
            ['name' => 'Marketplace Platform Development', 'category' => 'Custom Software Development', 'description' => 'Service marketplaces, booking platforms, multi-party workflows, and transaction-enabled digital platforms.'],
            ['name' => 'Admin Dashboard Development', 'category' => 'Custom Software Development', 'description' => 'Admin dashboards, reporting consoles, internal review tools, and operational control panels.'],
            ['name' => 'SaaS Product Development', 'category' => 'SaaS Product Development', 'description' => 'Subscription-based platforms, internal SaaS tools, customer portals, and scalable web software.'],
            ['name' => 'Client Portal Development', 'category' => 'SaaS Product Development', 'description' => 'Secure client workspaces, document portals, service dashboards, and customer self-service interfaces.'],
            ['name' => 'API Development and Integrations', 'category' => 'API Development & Integrations', 'description' => 'REST APIs, third-party integrations, automation bridges, and platform-to-platform data exchange.'],
            ['name' => 'Payment Gateway Integration', 'category' => 'API Development & Integrations', 'description' => 'Payment collection, payout workflows, mobile money integration, and transaction-ready platform setup.'],
            ['name' => 'Mobile App Development', 'category' => 'Mobile App Development', 'description' => 'Android, iOS, hybrid, and cross-platform mobile app builds.'],
            ['name' => 'App Maintenance and Support', 'category' => 'Mobile App Development', 'description' => 'App fixes, updates, store-readiness support, and ongoing application maintenance.'],
            ['name' => 'Progressive Web App Development', 'category' => 'Mobile App Development', 'description' => 'Installable web apps with mobile-friendly behavior and offline-ready experiences.'],
            ['name' => 'System Administration', 'category' => 'System Administration', 'description' => 'Server setup, system hardening, user access control, and routine systems management.'],
            ['name' => 'Cloud Infrastructure Setup', 'category' => 'Cloud Infrastructure', 'description' => 'Cloud hosting, deployments, VPS environments, scaling, and production readiness support.'],
            ['name' => 'DevOps and CI CD Setup', 'category' => 'DevOps & CI/CD', 'description' => 'Deployment pipelines, automated builds, release flow setup, and environment consistency.'],
            ['name' => 'Cybersecurity Services', 'category' => 'Cybersecurity Services', 'description' => 'Security reviews, hardening, risk reduction, and security guidance for digital platforms.'],
            ['name' => 'Security Audit and Penetration Testing', 'category' => 'Security Audit & Penetration Testing', 'description' => 'Vulnerability checks, application security review, and penetration testing support.'],
            ['name' => 'IT Support and Helpdesk', 'category' => 'IT Support & Helpdesk', 'description' => 'Technical troubleshooting, remote IT support, and recurring operational support.'],
            ['name' => 'Database Administration', 'category' => 'Database Administration', 'description' => 'Database setup, optimization, migration, backups, and operational database support.'],
            ['name' => 'QA and Software Testing', 'category' => 'QA & Software Testing', 'description' => 'Manual testing, test planning, QA review, and release readiness support.'],
            ['name' => 'Business Systems Automation', 'category' => 'Business Systems Automation', 'description' => 'Workflow automation, operational process improvement, and software-driven business efficiency.'],
            ['name' => 'ERP and CRM Setup', 'category' => 'ERP & CRM Setup', 'description' => 'CRM setup, ERP onboarding, business process implementation, and platform configuration.'],
            ['name' => 'Workflow Automation Design', 'category' => 'Automation & Integrations', 'description' => 'Automation architecture, process mapping, trigger design, and cross-tool workflow planning.'],
            ['name' => 'WhatsApp Chatbot Setup', 'category' => 'Automation & Integrations', 'description' => 'WhatsApp chatbot flows, automated replies, support routing, and lead capture messaging setup.'],
            ['name' => 'CRM Workflow Automation', 'category' => 'Business Systems Automation', 'description' => 'Pipeline automation, sales workflow logic, reminders, and customer movement automation inside CRM tools.'],
            ['name' => 'Lead Capture Automation', 'category' => 'Business Systems Automation', 'description' => 'Lead forms, qualification flow, routing, follow-up triggers, and handoff automation for sales-ready pipelines.'],
            ['name' => 'CRM Data Migration and Cleanup', 'category' => 'ERP & CRM Setup', 'description' => 'CRM import preparation, contact cleanup, field mapping, and structured data migration support.'],
            ['name' => 'UI UX Design', 'category' => 'UI/UX Design', 'description' => 'Product interface design, UX planning, wireframes, and design systems.'],
            ['name' => 'Graphic Design', 'category' => 'Graphic Design', 'description' => 'Brand visuals, campaign design, social graphics, marketing materials, and presentation assets.'],
            ['name' => 'Social Media Creative Design', 'category' => 'Graphic Design', 'description' => 'Static creatives, campaign posts, promotional visuals, and branded assets designed for social platforms.'],
            ['name' => 'Print and Flyer Design', 'category' => 'Graphic Design', 'description' => 'Flyers, posters, brochures, roll-up banners, and print-ready promotional design assets.'],
            ['name' => 'Brand Identity Design', 'category' => 'Brand Identity Design', 'description' => 'Logo systems, brand direction, visual identity, and branding guidelines.'],
            ['name' => 'Logo Design', 'category' => 'Brand Identity Design', 'description' => 'Primary logo concepts, brand marks, logo systems, and visual direction for business identity.'],
            ['name' => 'Presentation Design', 'category' => 'Presentation Design', 'description' => 'Business presentations, investor decks, internal reports, and polished visual slides.'],
            ['name' => 'Pitch Deck Design', 'category' => 'Presentation Design', 'description' => 'Investor decks, sales decks, proposal presentations, and high-clarity business storytelling slides.'],
            ['name' => 'Product Prototype Design', 'category' => 'Product Design', 'description' => 'Clickable prototypes, user-flow visuals, early product mockups, and concept validation screens.'],
            ['name' => 'Motion Graphics', 'category' => 'Motion Graphics', 'description' => 'Animated visual content for ads, promotions, explainers, and digital campaigns.'],
            ['name' => 'Video Editing', 'category' => 'Video Editing', 'description' => 'Promotional videos, business videos, short-form edits, and social-ready editing support.'],
            ['name' => 'Bookkeeping Support', 'category' => 'Bookkeeping & Accounting', 'description' => 'Ongoing bookkeeping, transaction cleanup, account organization, and routine financial record support.'],
            ['name' => 'Monthly Reconciliation Support', 'category' => 'Bookkeeping & Accounting', 'description' => 'Monthly account checks, reconciliation support, ledger balancing, and close-readiness for internal finance control.'],
            ['name' => 'Payroll Administration Support', 'category' => 'Payroll Support', 'description' => 'Payroll preparation, staff payment coordination, deductions review, and recurring payroll process support.'],
            ['name' => 'Financial Reporting Pack', 'category' => 'Financial Reporting', 'description' => 'Monthly and quarterly reporting packs, management summaries, and finance views for decision-making.'],
            ['name' => 'Tax Filing Preparation Support', 'category' => 'Tax Preparation Support', 'description' => 'Tax-ready documentation support, filing preparation, and structured finance handoff before submission.'],
            ['name' => 'Invoicing and Billing Operations', 'category' => 'Invoicing & Billing Operations', 'description' => 'Invoice preparation, billing follow-up coordination, and receivables workflow support for service businesses.'],
            ['name' => 'Budgeting and Forecast Planning', 'category' => 'Budgeting & Forecasting', 'description' => 'Budget templates, operating forecasts, planning support, and financial outlook preparation for growing teams.'],
            ['name' => 'Accounts Payable Support', 'category' => 'Bookkeeping & Accounting', 'description' => 'Supplier invoice handling, payable tracking, payment scheduling, and recurring vendor payment support for internal finance teams.'],
            ['name' => 'Accounts Receivable Support', 'category' => 'Bookkeeping & Accounting', 'description' => 'Receivable tracking, collection follow-up structure, client billing support, and overdue invoice coordination.'],
            ['name' => 'Cash Flow Tracking Setup', 'category' => 'Budgeting & Forecasting', 'description' => 'Cash flow visibility setup, tracking templates, movement planning, and decision-ready operating cash views.'],
            ['name' => 'Expense Tracking and Cleanup', 'category' => 'Bookkeeping & Accounting', 'description' => 'Expense categorization, record cleanup, internal spending visibility, and reporting-ready transaction organization.'],
            ['name' => 'Management Accounts Preparation', 'category' => 'Financial Reporting', 'description' => 'Management accounts, internal finance summaries, recurring reporting packs, and structured financial snapshots for operators.'],
            ['name' => 'Financial Controls Review', 'category' => 'Financial Reporting', 'description' => 'Finance process review, control points, operational safeguards, and recommendations that improve internal accountability.'],
            ['name' => 'Social Media Management', 'category' => 'Social Media Management', 'description' => 'Content planning, posting, account management, moderation, and channel performance support.', 'default_brief_template' => 'Describe the platforms you want managed, your audience, the type of content you need, and the result you want to achieve.'],
            ['name' => 'Instagram Management', 'category' => 'Social Media Management', 'description' => 'Instagram content planning, posting cadence, community handling, and profile growth support.'],
            ['name' => 'Facebook Page Management', 'category' => 'Social Media Management', 'description' => 'Facebook content operations, inbox moderation, posting support, and business page management.'],
            ['name' => 'YouTube Channel Management', 'category' => 'Social Media Management', 'description' => 'Channel organization, content scheduling, upload support, metadata handling, and growth coordination for YouTube.'],
            ['name' => 'TikTok Content Management', 'category' => 'Social Media Management', 'description' => 'Short-form content planning, publishing support, and audience rhythm management for TikTok channels.'],
            ['name' => 'Content Calendar Planning', 'category' => 'Social Media Management', 'description' => 'Monthly content planning, posting calendars, campaign structure, and channel-by-channel publishing guidance.'],
            ['name' => 'Social Media Audit', 'category' => 'Social Media Management', 'description' => 'Channel review, performance diagnosis, profile cleanup recommendations, and content direction insights.'],
            ['name' => 'Community Management', 'category' => 'Community Management', 'description' => 'Audience engagement, response handling, moderation, and community support across social channels.'],
            ['name' => 'Content Design', 'category' => 'Content Design', 'description' => 'Structured content for websites, campaigns, products, and customer education.'],
            ['name' => 'Copywriting', 'category' => 'Copywriting', 'description' => 'Sales copy, web copy, campaign copy, product messaging, and brand writing.'],
            ['name' => 'Technical Writing', 'category' => 'Technical Writing', 'description' => 'Documentation, product guides, SOPs, manuals, and internal knowledge content.'],
            ['name' => 'SEO Services', 'category' => 'SEO', 'description' => 'Search optimization, on-page SEO, technical SEO, and search visibility improvements.'],
            ['name' => 'Digital Marketing', 'category' => 'Digital Marketing', 'description' => 'Campaign planning, online growth support, digital acquisition, and marketing execution.'],
            ['name' => 'Performance Marketing', 'category' => 'Performance Marketing', 'description' => 'Paid ads, conversion campaigns, audience targeting, and measurable growth campaigns.'],
            ['name' => 'Meta Ads Management', 'category' => 'Performance Marketing', 'description' => 'Facebook and Instagram ad planning, audience targeting, budget handling, and campaign optimization support.'],
            ['name' => 'Google Ads Management', 'category' => 'Performance Marketing', 'description' => 'Search ads, display campaigns, conversion-oriented traffic acquisition, and performance optimization.'],
            ['name' => 'Email Marketing', 'category' => 'Email Marketing', 'description' => 'Email campaigns, mailing flow setup, nurture sequences, and newsletter operations.'],
            ['name' => 'Analytics and Dashboards', 'category' => 'Analytics & Dashboards', 'description' => 'Reporting dashboards, business insights, KPI tracking, and decision-ready data views.'],
            ['name' => 'Article and Blog Writing', 'category' => 'Content Writing', 'description' => 'Articles, blog posts, editorial content, and structured writing that supports publishing and audience education.'],
            ['name' => 'Website and Campaign Copywriting', 'category' => 'Content Writing', 'description' => 'Website copy, campaign messaging, landing page text, and conversion-ready business writing.'],
            ['name' => 'Script Writing Support', 'category' => 'Script Writing', 'description' => 'Scripts for videos, ads, explainers, interviews, podcasts, and presentation-led storytelling.'],
            ['name' => 'Voice Over Recording Support', 'category' => 'Voice Over & Audio Production', 'description' => 'Voice-over production support for explainer videos, ads, training materials, and public-facing media assets.'],
            ['name' => 'Podcast Editing and Production', 'category' => 'Podcast Production', 'description' => 'Podcast editing, audio cleanup, episode packaging, and publishing-ready production support.'],
            ['name' => 'Translation and Transcription Support', 'category' => 'Translation & Transcription', 'description' => 'Translation, transcription, bilingual content handling, and transcript preparation for business and media use.'],
            ['name' => 'Media Kit and PR Pack Preparation', 'category' => 'Public Relations & Media Kits', 'description' => 'Media kits, press packs, company fact sheets, and structured communication packs for public-facing outreach.'],
            ['name' => 'Newsletter Planning and Production', 'category' => 'Newsletter Production', 'description' => 'Newsletter copy, issue planning, publishing rhythm, and communication support for email-based updates.'],
            ['name' => 'Press Release Writing', 'category' => 'Public Relations & Media Kits', 'description' => 'Press releases, announcement drafts, public updates, and media-facing communication support for launches and milestones.'],
            ['name' => 'Speech Writing Support', 'category' => 'Script Writing', 'description' => 'Speech drafts, keynote support, public remarks, and presentation-led writing for leaders and institutions.'],
            ['name' => 'Case Study Writing', 'category' => 'Content Writing', 'description' => 'Case studies, proof-of-work narratives, impact summaries, and customer success storytelling for business credibility.'],
            ['name' => 'Interview Transcription', 'category' => 'Translation & Transcription', 'description' => 'Interview transcript preparation, meeting transcript cleanup, and structured text conversion from recorded conversations.'],
            ['name' => 'Subtitling and Caption Support', 'category' => 'Voice Over & Audio Production', 'description' => 'Subtitle preparation, caption cleanup, and publishing-ready text overlays for videos and recorded media assets.'],
            ['name' => 'Content Repurposing Support', 'category' => 'Content Writing', 'description' => 'Turn one source asset into multiple publishable outputs across articles, newsletters, short-form content, and communication packs.'],
            ['name' => 'Bulk SMS Integration', 'category' => 'Bulk SMS & Messaging Solutions', 'description' => 'Bulk SMS system setup, SMS gateway integration, OTP messaging, and transactional SMS support.'],
            ['name' => 'Bulk SMS Campaign Management', 'category' => 'Bulk SMS & Messaging Solutions', 'description' => 'Campaign planning, contact handling, message delivery coordination, and SMS operations.'],
            ['name' => 'WhatsApp Business Integration', 'category' => 'Bulk SMS & Messaging Solutions', 'description' => 'WhatsApp business workflow setup, support flows, message automation, and customer touchpoints.'],
            ['name' => 'Digital Card Design', 'category' => 'Digital Cards & Smart Profiles', 'description' => 'Digital business cards, smart profile pages, and lightweight public business profiles.'],
            ['name' => 'Smart Profile Setup', 'category' => 'Digital Cards & Smart Profiles', 'description' => 'Public profile pages, digital contact experiences, and online presence setup.'],
            ['name' => 'Data Entry and Virtual Assistance', 'category' => 'Data Entry & Virtual Assistance', 'description' => 'Structured data tasks, back-office admin work, coordination support, and operational assistance.'],
            ['name' => 'Secure Server Monitoring', 'category' => 'System Administration', 'description' => 'Server health monitoring, alert routing, service uptime checks, and proactive operational oversight.'],
            ['name' => 'Backup and Disaster Recovery Setup', 'category' => 'Cloud Infrastructure', 'description' => 'Backup planning, recovery readiness, restore testing, and continuity setup for critical systems.'],
            ['name' => 'Vulnerability Assessment', 'category' => 'Cybersecurity Services', 'description' => 'Security weakness review, exposure mapping, prioritized remediation findings, and technical risk visibility.'],
            ['name' => 'Network Security Hardening', 'category' => 'Cybersecurity Services', 'description' => 'Network access review, firewall guidance, endpoint protection posture, and environment hardening support.'],
            ['name' => 'Incident Response Support', 'category' => 'Cybersecurity Services', 'description' => 'Security incident triage, containment guidance, issue tracking, and post-incident recovery coordination.'],
            ['name' => 'Security Awareness Training', 'category' => 'Cybersecurity Services', 'description' => 'Staff security awareness guidance, phishing readiness, safe access habits, and digital risk education support.'],
            ['name' => 'Business Registration with BRELA', 'category' => 'Government Consultancy Services', 'description' => 'Guidance and processing support for business registration through BRELA.', 'default_brief_template' => 'Describe the type of registration you need, the documents already available, and any deadline or compliance requirement you are working against.'],
            ['name' => 'Company Registration with BRELA', 'category' => 'Government Consultancy Services', 'description' => 'Support for company registration steps, requirements, and filing preparation through BRELA.'],
            ['name' => 'Business Name Registration with BRELA', 'category' => 'Government Consultancy Services', 'description' => 'Support for business name registration, paperwork guidance, and procedural follow-through.'],
            ['name' => 'NIDA Application Support', 'category' => 'Government Consultancy Services', 'description' => 'Support around NIDA application steps, corrections, and identification process guidance.'],
            ['name' => 'RITA Birth Certificate Support', 'category' => 'Government Consultancy Services', 'description' => 'Application support and process guidance for birth certificate workflows.'],
            ['name' => 'RITA Death Certificate Support', 'category' => 'Government Consultancy Services', 'description' => 'Application support and process guidance for death certificate workflows.'],
            ['name' => 'Business License Support', 'category' => 'Government Consultancy Services', 'description' => 'Business licensing support, filing preparation, and follow-up for licensing workflows.'],
            ['name' => 'TAUSI License Follow Up', 'category' => 'Government Consultancy Services', 'description' => 'Follow-up support for TAUSI and related licensing steps.'],
            ['name' => 'TIN and Tax Registration Support', 'category' => 'Government Consultancy Services', 'description' => 'Support for TIN registration, tax readiness, and compliance-related onboarding.'],
            ['name' => 'VAT Registration Support', 'category' => 'Government Consultancy Services', 'description' => 'Guidance and process support for VAT registration and related business compliance steps.'],
            ['name' => 'Work Permit Support', 'category' => 'Government Consultancy Services', 'description' => 'Application support and process guidance for work permits and supporting compliance requirements.'],
            ['name' => 'Residence Permit Support', 'category' => 'Government Consultancy Services', 'description' => 'Support for residence permit-related application workflows and supporting documents.'],
            ['name' => 'OSHA Registration Support', 'category' => 'Government Consultancy Services', 'description' => 'OSH-related registration support, process guidance, and compliance preparation.'],
            ['name' => 'NSSF Registration Support', 'category' => 'Government Consultancy Services', 'description' => 'Support for NSSF registration and employer compliance onboarding.'],
            ['name' => 'WCF Registration Support', 'category' => 'Government Consultancy Services', 'description' => 'Support for workers compensation registration and related compliance handling.'],
            ['name' => 'Trademark Filing Support', 'category' => 'Government Consultancy Services', 'description' => 'Guidance for trademark filing, document preparation, and filing workflow support.'],
            ['name' => 'NGO Registration Support', 'category' => 'Government Consultancy Services', 'description' => 'Guidance and filing support for NGO registration processes, supporting documents, and compliance follow-through.'],
            ['name' => 'Tender Documentation Support', 'category' => 'Government Consultancy Services', 'description' => 'Tender response preparation, document review, submission readiness, and compliance support for formal bids.'],
            ['name' => 'Tax Clearance Support', 'category' => 'Government Consultancy Services', 'description' => 'Process support for tax clearance-related requirements, supporting documents, and submission readiness.'],
            ['name' => 'Compliance Document Preparation', 'category' => 'Government Consultancy Services', 'description' => 'Structured preparation of compliance documents, supporting packs, and readiness material for regulated processes.'],
            ['name' => 'Research Summary Pack', 'category' => 'Research Support', 'description' => 'Structured research summaries, desk research support, source gathering, and insight packs for business or institutional work.'],
            ['name' => 'Market and Competitor Research Support', 'category' => 'Research Support', 'description' => 'Competitor review, market scan support, research notes, and comparative analysis for planning and positioning.'],
            ['name' => 'Proposal and Grant Writing Support', 'category' => 'Proposal & Grant Writing', 'description' => 'Business proposals, donor-facing submissions, grant support, and structured bid writing for formal applications.'],
            ['name' => 'SOP and Policy Manual Development', 'category' => 'SOP & Policy Documentation', 'description' => 'Operational SOPs, policy manuals, internal rules, and documentation that helps teams run with consistency.'],
            ['name' => 'Training Deck and Manual Creation', 'category' => 'Training Materials Development', 'description' => 'Training decks, participant manuals, onboarding packs, and session-ready learning materials for staff or partners.'],
            ['name' => 'Monitoring and Evaluation Reporting', 'category' => 'Monitoring & Evaluation Reporting', 'description' => 'Monitoring reports, indicator narratives, progress summaries, and structured reporting for program delivery.'],
            ['name' => 'Workshop Agenda and Facilitation Pack', 'category' => 'Workshop & Facilitation Support', 'description' => 'Workshop agendas, facilitation guides, participant flow materials, and session support documents for trainings and events.'],
            ['name' => 'Project Concept Note Writing', 'category' => 'Proposal & Grant Writing', 'description' => 'Concept notes, early project framing documents, and structured summaries used to shape formal proposals or donor conversations.'],
            ['name' => 'Business Proposal Writing', 'category' => 'Proposal & Grant Writing', 'description' => 'Business proposals, commercial offer documents, and structured submissions designed to win formal work or partnerships.'],
            ['name' => 'Donor Reporting Support', 'category' => 'Monitoring & Evaluation Reporting', 'description' => 'Donor-facing progress reports, narrative support, compliance-ready updates, and structured reporting for funded work.'],
            ['name' => 'Employee Handbook Development', 'category' => 'SOP & Policy Documentation', 'description' => 'Employee handbooks, workplace guidance packs, internal expectations, and people-operations documents for growing teams.'],
            ['name' => 'Operations Manual Development', 'category' => 'SOP & Policy Documentation', 'description' => 'Operational manuals, department process guides, and internal operating documents that improve repeatability and control.'],
            ['name' => 'Research Interview Guide Preparation', 'category' => 'Research Support', 'description' => 'Interview guides, research prompts, field conversation structure, and preparation support for formal information gathering.'],
        ];
    }
}
