export const wolfixServiceCategories = [
  'Software Engineering',
  'Web Development',
  'Mobile App Development',
  'Website Design',
  'Website Maintenance',
  'E-Commerce Development',
  'WordPress Development',
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Custom Software Development',
  'SaaS Product Development',
  'API Development & Integrations',
  'System Administration',
  'Cloud Infrastructure',
  'DevOps & CI/CD',
  'Cybersecurity Services',
  'Security Audit & Penetration Testing',
  'IT Support & Helpdesk',
  'Database Administration',
  'QA & Software Testing',
  'Business Systems Automation',
  'Government Consultancy Services',
  'UI/UX Design',
  'Graphic Design',
  'Brand Identity Design',
  'Presentation Design',
  'Motion Graphics',
  'Video Editing',
  'Product Design',
  'Social Media Management',
  'Community Management',
  'Content Design',
  'Copywriting',
  'Technical Writing',
  'SEO',
  'Digital Marketing',
  'Performance Marketing',
  'Email Marketing',
  'Automation & Integrations',
  'Analytics & Dashboards',
  'Bulk SMS & Messaging Solutions',
  'Digital Cards & Smart Profiles',
  'Data Entry & Virtual Assistance',
  'ERP & CRM Setup',
] as const;

export const wolfixMarketplaceLanes = [
  'Software engineering delivery',
  'Websites, apps, and digital product buildouts',
  'Infrastructure, systems, and security support',
  'Government consultancy and compliance support',
  'Graphic design and brand systems',
  'Social media and digital campaign support',
  'Content, growth, and analytics operations',
] as const;

export const wolfixServiceSearchSuggestions = [
  'Website development',
  'Website design',
  'Website redesign',
  'Website maintenance',
  'Website speed optimization',
  'Website bug fixing',
  'Website migration',
  'Website security hardening',
  'Company website',
  'Corporate website',
  'Business website',
  'Business website redesign',
  'Landing page design',
  'Landing page development',
  'Sales funnel landing page',
  'Portfolio website design',
  'E-commerce website',
  'E-commerce store setup',
  'Online store development',
  'WooCommerce development',
  'Shopify store setup',
  'Shopify theme customization',
  'E-commerce payment integration',
  'WordPress website',
  'WordPress development',
  'WordPress maintenance',
  'WordPress customization',
  'WordPress plugin setup',
  'WordPress theme development',
  'Portfolio website',
  'Personal portfolio website',
  'Blog website development',
  'News website development',
  'Membership website development',
  'School management system',
  'Hospital management system',
  'Inventory management system',
  'ERP system development',
  'CRM system setup',
  'POS system development',
  'HR management system',
  'Payroll system setup',
  'Library management system',
  'Property management system',
  'Booking system development',
  'Marketplace platform development',
  'Accounting software setup',
  'Billing system development',
  'Invoicing software setup',
  'Custom software development',
  'Enterprise software development',
  'Business software development',
  'SaaS application development',
  'Product MVP development',
  'Web application development',
  'Admin dashboard development',
  'Customer portal development',
  'Internal tools development',
  'Mobile app development',
  'Android app development',
  'iOS app development',
  'Flutter app development',
  'React Native app development',
  'Hybrid app development',
  'Progressive web app development',
  'App maintenance and support',
  'Frontend development',
  'React frontend development',
  'Next.js development',
  'Vue.js frontend development',
  'Angular frontend development',
  'Backend development',
  'Node.js backend development',
  'Laravel backend development',
  'PHP backend development',
  'Python backend development',
  'Java backend development',
  'Go backend development',
  'API integration',
  'REST API development',
  'GraphQL API development',
  'Third-party API integration',
  'CRM API integration',
  'ERP API integration',
  'Payment gateway integration',
  'Mobile money integration',
  'Stripe integration',
  'PayPal integration',
  'Webhook integration',
  'System administration',
  'Linux system administration',
  'Windows server administration',
  'Server monitoring setup',
  'Server setup and maintenance',
  'Cloud deployment',
  'Cloud infrastructure setup',
  'AWS cloud setup',
  'Azure cloud setup',
  'Google Cloud setup',
  'VPS deployment',
  'Docker deployment',
  'Kubernetes support',
  'DevOps support',
  'CI CD pipeline setup',
  'Infrastructure automation',
  'Cybersecurity audit',
  'Cybersecurity consulting',
  'Security audit',
  'Application security review',
  'Website vulnerability assessment',
  'Network security assessment',
  'Penetration testing',
  'Security monitoring setup',
  'Firewall configuration',
  'Access control review',
  'Security incident response',
  'Database administration',
  'Database optimization',
  'Database migration',
  'MySQL administration',
  'PostgreSQL administration',
  'Backup and disaster recovery',
  'IT support and helpdesk',
  'Technical support',
  'Remote IT support',
  'System troubleshooting',
  'UI UX design',
  'UX research',
  'Wireframe design',
  'Prototype design',
  'Design system creation',
  'Product interface design',
  'Graphic design',
  'Social media graphic design',
  'Banner design',
  'Brochure design',
  'Flyer design',
  'Presentation design',
  'Brand identity design',
  'Logo design',
  'Brand guideline design',
  'Packaging design',
  'Motion graphics',
  'Video editing',
  'Short form video editing',
  'YouTube video editing',
  'Promotional video editing',
  'Social media management',
  'Social media strategy',
  'Social media content planning',
  'Community management',
  'Digital marketing',
  'Performance marketing',
  'Google Ads management',
  'Facebook Ads management',
  'Lead generation campaigns',
  'SEO services',
  'Technical SEO',
  'Local SEO',
  'On-page SEO',
  'SEO audit',
  'Content writing',
  'Blog writing',
  'Website copywriting',
  'Email copywriting',
  'Copywriting',
  'Technical writing',
  'Proposal writing',
  'Documentation writing',
  'Analytics dashboard setup',
  'Business intelligence dashboards',
  'Power BI dashboard setup',
  'Looker Studio dashboard setup',
  'Data visualization',
  'Automation and integrations',
  'Workflow automation',
  'Zapier automation',
  'Make automation',
  'CRM automation',
  'Email automation',
  'Bulk SMS integration',
  'Bulk SMS platform setup',
  'SMS gateway integration',
  'Transactional SMS setup',
  'OTP SMS integration',
  'USSD and SMS integration',
  'WhatsApp Business integration',
  'Telegram bot setup',
  'Chatbot setup',
  'Digital business card design',
  'Digital business card development',
  'Smart business card setup',
  'NFC business card profile setup',
  'Digital profile card design',
  'Virtual business card',
  'Link in bio page design',
  'Personal profile landing page',
  'CRM setup',
  'ERP implementation',
  'Government consultancy',
  'Business registration with BRELA',
  'Company registration with BRELA',
  'Business name registration with BRELA',
  'Company incorporation support',
  'BRELA annual return filing support',
  'BRELA compliance support',
  'NIDA application support',
  'NIDA number follow-up support',
  'NIDA correction support',
  'NIDA record update support',
  'RITA birth certificate application',
  'Birth certificate follow-up',
  'RITA death certificate application',
  'Death certificate follow-up',
  'Marriage certificate support',
  'Divorce record support',
  'Business license application',
  'Municipal business license support',
  'TAUSI business license follow-up',
  'Trading license renewal support',
  'TIN registration support',
  'TRA tax clearance support',
  'VAT registration support',
  'EFD machine registration support',
  'Tax objection support',
  'Work permit application support',
  'Residence permit support',
  'OSHA registration support',
  'NSSF registration support',
  'WCF registration support',
  'TFDA application support',
  'TMDA application support',
  'Tender submission support',
  'NGO registration support',
  'Patent and trademark filing support',
  'Social media account setup',
  'Social media page management',
  'Instagram management',
  'Facebook page management',
  'TikTok account management',
  'LinkedIn page management',
  'Social media content calendar',
  'Social media posting service',
  'Social media advertising',
  'Social media growth strategy',
  'Social media moderation',
  'Social media reporting',
  'Influencer campaign coordination',
  'Reels and short video content',
  'YouTube channel management',
  'Compliance support',
  'Regulatory compliance support',
  'Policy documentation support',
  'Tender documentation support',
  'Business registration support',
  'Tax compliance support',
] as const;
